/**
 * 100 suggestions for the new chat page, covering knowledge work, analysis, reporting, and data tasks.
 * These are randomly selected each time the user loads the new chat page.
 */
export const chatSuggestions = [
  'Analyze this spreadsheet and identify trends or patterns',
  'Extract data from this PDF and create a summary',
  'Create a report comparing data from multiple sources',
  'Clean and standardize data in this spreadsheet',
  'Convert this PDF table into a spreadsheet format',
  'Generate charts and visualizations from this data',
  'Merge data from multiple spreadsheets into one',
  'Extract text and tables from these PDF documents',
  'Analyze survey responses and summarize key findings',
  'Create a dashboard to track key metrics over time',
  'Format and organize this document for better readability',
  'Find duplicates and inconsistencies in this dataset',
  'Convert this spreadsheet into a formatted report',
  'Extract specific information from multiple PDFs',
  'Calculate summary statistics from this data',
  'Create a script to automate this repetitive spreadsheet task',
  'Analyze sales data and identify top performers',
  'Combine data from different sources into one analysis',
  'Extract and organize contact information from documents',
  'Create pivot tables and summaries from this data',
  'Parse invoice data from PDFs into a structured format',
  'Identify outliers and anomalies in this dataset',
  'Generate a monthly report from raw data',
  'Convert this document into a different format',
  'Analyze customer feedback and extract themes',
  'Create formulas to calculate complex metrics',
  'Extract tables from PDFs and convert to spreadsheets',
  'Compare data across different time periods',
  'Clean up formatting inconsistencies in this spreadsheet',
  'Generate a summary report from multiple data sources',
  'Analyze financial data and highlight key insights',
  'Extract specific sections from multiple PDF documents',
  'Create data visualizations to present findings',
  'Merge customer data from different systems',
  'Parse structured data from unstructured documents',
  'Calculate percentages and growth rates from this data',
  'Extract and organize meeting notes from PDFs',
  'Create a template for recurring reports',
  'Analyze website analytics and identify trends',
  'Convert this CSV file into a formatted spreadsheet',
  'Extract key metrics from financial reports',
  'Create a script to process multiple files automatically',
  'Analyze email data and identify patterns',
  'Format this document for professional presentation',
  'Extract data from forms and organize into a database',
  'Generate comparison charts between different datasets',
  'Clean up and validate data entries',
  'Extract quotes and citations from research papers',
  'Create automated reports that update regularly',
  'Analyze social media metrics and engagement',
  'Convert this spreadsheet into a PDF report',
  'Extract and organize product information from catalogs',
  'Identify correlations between different data points',
  'Create a data entry form with validation',
  'Extract contact details from business cards or documents',
  'Generate executive summaries from detailed reports',
  'Analyze customer churn and retention data',
  'Convert PDF forms into fillable digital formats',
  'Create pivot analyses from complex datasets',
  'Extract and organize research findings from papers',
  'Generate time-series analysis from historical data',
  'Format this spreadsheet for printing or sharing',
  'Extract specific data points from multiple sources',
  'Create a dashboard to monitor key performance indicators',
  'Analyze text data and extract key themes',
  'Convert this report into a presentation format',
  'Extract and organize inventory data from documents',
  'Generate automated email reports from data',
  'Analyze A/B test results and provide recommendations',
  'Extract tables and charts from PDF reports',
  'Create data validation rules for data entry',
  'Merge customer records and remove duplicates',
  'Extract and organize meeting minutes from documents',
  'Generate statistical summaries from survey data',
  'Convert this data into a different file format',
  'Analyze market research data and identify opportunities',
  'Extract key information from legal documents',
  'Create conditional formatting rules for data visualization',
  'Generate comparison reports between different periods',
  'Extract and organize product specifications from PDFs',
  'Analyze customer satisfaction scores and trends',
  'Convert handwritten notes into digital format',
  'Create automated workflows for data processing',
  'Extract contact information from email signatures',
  'Generate progress reports from project data',
  'Analyze website traffic patterns and user behavior',
  'Extract data from invoices and create expense reports',
  'Create data entry templates with built-in validation',
  'Merge data from different departments',
  'Extract and organize research citations',
  'Generate performance dashboards from raw metrics',
  'Analyze customer demographics and segmentation',
  'Convert PDF presentations into editable formats',
  'Create scripts to automate data collection',
  'Extract key metrics from business reports',
  'Generate trend analysis from historical data',
  'Format documents for different audiences',
  'Extract and organize product reviews and feedback',
  'Create data visualization dashboards',
  'Analyze competitor data and market positioning',
  'Extract structured data from unstructured text',
  'Generate automated alerts based on data thresholds',
  'Convert spreadsheets into interactive web dashboards',
  'Extract and organize event information from documents',
  'Create reports that combine quantitative and qualitative data'
];

/**
 * Get a random suggestion from the list.
 * Uses Math.random() which is sufficient for this use case.
 */
export function getRandomSuggestion(): string {
  const randomIndex = Math.floor(Math.random() * chatSuggestions.length);
  return chatSuggestions[randomIndex];
}
